version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php-localy:1.0.0
    container_name: sample-api
    restart: unless-stopped
    working_dir: /app
    network_mode: "host"
    ports:
      - 8000:8000
    volumes:
      - ./sample-api:/app
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=xpto